
server:
  port: 90

scenario:
  jwt:
    key: kyckyc123456789123456789123456789
    alg: HS256
    typ: JWT
board:
  check:
    url:
      EDUCATION_BOARD_URL: http://localhost:90/api/user/board/education
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simsim?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: youngchulkim@oracleadinfo.com
    password: yckoracle1234


logging:
  level:
    org:
      springframework:
        security:
          web: debug
    com:
      test:
        scenario:
          security: debug
